title: studyguides.science
email: hello@studyguides.science
description: >
  A collection of science notes for school use.
baseurl: ""
url: "https://studyguides.science"
host: localhost

# Build settings
port: 4000
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
sass:
    sass_dir: _sass
plugins_dir:
 - jekyll-coffeescript

collections:
  biology:
    output: true
    permalink: /category/:collection/:title
  chemistry:
    output: true
    permalink: /category/:collection/:title

defaults:
  -
    scope:
      path: ""
      type: pages
    values:
      layout: default
  -
    scope:
      path: ""
      type: guides
    values:
      layout: guide
  -
    scope:
      path: ""
      type: category
    values:
      layout: category