---
title: studyguides.science
timezone: UTC
collections:
  category:
    title: Category
    output: true
    permalink: "/:collection/:title"
    layout: "category"
    type: "categories"
  guide:
    title: Guide
    output: true
    permalink: "/category/:categories/:title"
    layout: "guide"
defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: default
- scope:
    path: ''
    type: guides
  values:
    layout: guide
- scope:
    path: ''
    type: category
  values:
    layout: category
email: hello@studyguides.science
description: 'A collection of science notes for school use.

'
baseurl: 
url: https://studyguides.science
host: localhost
port: 4000
markdown: kramdown
theme: minima
gems:
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
sass:
  sass_dir: _sass
plugins_dir:
- jekyll-minifier
